### ISSUE TITLE
在linux下时，阴影部分是黑色的。

### ISSUE THREAD

**Issue by xinsuinizhuan** [xtuer/template-app#3]

**Comment by xtuer** [comment]
我没有 Linux 的 Gui 环境，您可以尝试换一下背景图试试看是不是还有这个问题。

**Comment by xinsuinizhuan** [comment]
不是背景的问题，是九宫格画阴影的问题，我把topwindows.h中：
 explicit TopWindow(QWidget *centralWidget,
//                       const QMargins &windowPaddings     = QMargins(16, 10, 16, 16),
//                       const QMargins &borderImageBorders = QMargins(23, 13, 23, 33),
                       const QMargins &windowPaddings     = QMargins(1, 1, 1, 1),
                       const QMargins &borderImageBorders = QMargins(1, 1, 1, 1),
                       const QString  &borderImagePath    = QString("img/top-window/shadow.png"),
                       bool  borderImageHorizontalStretch = true,
                       bool  borderImageVerticalStretch   = true);
    ~TopWindow() override;
设置为1,1,1,1后，黑白就很小了，宽度只有1了。
